version: '3.8'
services:
  app:
    image: node:20
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start"
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6379:6379'
