name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'provisioning/**'
      - '.github/workflows/deploy-infrastructure.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd provisioning
          npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOYMENT_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CDK Stack
        run: |
          cd provisioning
          export SSL_CERT_DOMAIN=${{ env.SSL_CERT_DOMAIN }}
          export SSL_CERT_EMAIL=${{ env.SSL_CERT_EMAIL }}
          npx cdk deploy --all --require-approval never
